# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SPHTechPOC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift', '~> 4.2.0'
  pod 'RxCocoa', '~> 4.2.0'

  # Pods for SPHTechPOC

  target 'SPHTechPOCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SPHTechPOCUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
